source "https://rubygems.org"

gem 'sinatra'
gem 'service_manager'
gem 'activerecord'
gem 'sqlite3'

group :development do
  gem 'rake'
  gem 'cucumber'
  gem 'rspec'
  gem 'capybara'
  gem 'launchy'
  gem 'database_cleaner'
end
